### ISSUE TITLE
Using multiple binding on "QT_PREFERRED_BINDING" errors.

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-maya#65]
**Description**

Setting multiple bindings on "QT_PREFERRED_BINDING" errors ```pyblish-maya/vendor/Qt.py``` with the following;

```
pyblish-maya: Could not load integration: Traceback (most recent call last):
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\pythonpath\userSetup.py", line 3, in <module>
    __import__("pyblish_maya")
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\__init__.py", line 3, in <module>
    from .lib import (
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\lib.py", line 16, in <module>
    from .vendor.Qt import QtWidgets, QtGui
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\vendor\Qt.py", line 237, in <module>
    _init()
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\vendor\Qt.py", line 207, in _init
    "not available" % preferred)
ImportError: Preferred Qt binding "PySide;PySide2" not available
```

**Reproducible**

Before launching a ```pyblish-maya``` enabled Maya, set the following;

```python
os.environ["QT_PREFERRED_BINDING"] = "PySide" + os.pathsep + "PySide2"
```

**Comment by mottosso** [comment]
Looks like the version in pyblish-maya is old and doesn't support multiple bindings.
