### ISSUE TITLE
# ValueError: Could not locate Python executable.

### ISSUE THREAD

**Issue by monsteradurm** [pyblish/pyblish-maya#70]
Hi,
I am receiving the following error attempting to execute from Maya 2018.
**# ValueError: Could not locate Python executable.**

setup..
```
import sys, pyblish_qml, pyblish, pyblish_maya
sys.path.append(r'G:\_PIPELINE_MANAGEMENT\_externalPythonLibraries\pyblish_maya\pythonpath')
pyblish.api.register_gui("pyblish_qml")
pyblish_maya.setup()
pyblish_maya.show()
```

error result
```
pyblish: Deregistered g:/_PIPELINE_MANAGEMENT/_externalPythonLibraries\pyblish_maya\plugins
pyblish: Integration torn down successfully
pyblish: Registered g:/_PIPELINE_MANAGEMENT/_externalPythonLibraries\pyblish_maya\plugins
Pyblish loaded successfully.
Setting up Pyblish QML in Maya
# Traceback (most recent call last):
#   File "g:/_PIPELINE_MANAGEMENT/_externalPythonLibraries\pyblish_qml\host.py", line 132, in show
#     server = ipc.server.Server(service, targets=targets, modal=modal)
#   File "g:/_PIPELINE_MANAGEMENT/_externalPythonLibraries\pyblish_qml\ipc\server.py", line 111, in __init__
#     python = python or find_python()
#   File "g:/_PIPELINE_MANAGEMENT/_externalPythonLibraries\pyblish_qml\ipc\server.py", line 289, in find_python
#     raise ValueError("Could not locate Python executable.")
# ValueError: Could not locate Python executable.
```

**Comment by mottosso** [comment]
See [register_python_executable](https://github.com/pyblish/pyblish-qml#usage).
